### ISSUE TITLE
Please enforce HTTPs

### ISSUE THREAD

**Issue by lzblack** [dannydonahue5/WebTechProject#2]

**Comment by dannydonahue5** [comment]
![image](https://user-images.githubusercontent.com/112453133/199036642-4b1c3848-cece-405a-a19c-9279602f18de.png)

**Comment by dannydonahue5** [comment]
I am getting this alert, I am not sure why

**Comment by lzblack** [comment]
Can you take a screenshot of DNS settings from your domain provider? Remember to remove sensitive information.

**Comment by dannydonahue5** [comment]
![image](https://user-images.githubusercontent.com/112453133/199040045-219f3c1e-a960-4e57-8f48-5f693f8b457e.png)

**Comment by dannydonahue5** [comment]
I got the domain from namecheap

**Comment by lzblack** [comment]
Could you show me the screenshot of Advanced DNS settings? You need to click "MANAGE" button.

**Comment by dannydonahue5** [comment]
![image](https://user-images.githubusercontent.com/112453133/199286120-9b2a1473-2663-4e11-84a7-724119b3ef2f.png)

**Comment by dannydonahue5** [comment]
![image](https://user-images.githubusercontent.com/112453133/199286209-ab3a007c-36db-4099-8d0c-1e143e32cf0c.png)

**Comment by dannydonahue5** [comment]
Apologies for the late response

**Comment by lzblack** [comment]
Remove the first www record: 
![image](https://user-images.githubusercontent.com/1173076/199288747-71a5339d-1099-4c89-aedc-7af273ee01b9.png)

**Comment by dannydonahue5** [comment]
all set, have to wait until the certificate is issue then I can enforce HTTPS

**Comment by dannydonahue5** [comment]
thank you
