### ISSUE TITLE
Content Idea

### ISSUE THREAD

**Issue by kcarleton1** [dannydonahue5/WebTechProject#4]
Hi Danny! I think it would be pretty cool if you linked the "Yousician" application to your website. It would allow users to follow the same steps you did when playing guitar.

**Comment by kcarleton1** [comment]
Hi Danny! I really like the color scheme for your website, add some cool fonts to compliment the colors! Or maybe a cool border

**Comment by dannydonahue5** [comment]
Hi Kayla, thank you for the review! I like the idea of linking the app, and yes - I am still trying to figure out the color scheme and everything. I wanted to nail down the content first then worry about that. I started to add borders to the done pages.
