### ISSUE TITLE
Enrique Rodriguez's Peer Review

### ISSUE THREAD

**Issue by enriquerf** [dannydonahue5/WebTechProject#5]
Hi Danny, I really enjoyed going through your website. It is obvious that you took your time to make sure everything looks in order and the result of this effort definitely shows in this first version. It does look like you are still working on some pages so I tried to comment only on pages that looked like you have already started working on the content for them.

Although you definitely seem to be going in the right direction, here are my following suggestions for your next version:

- Homepage: consider using a grid or flex boxes for keeping a standard view of your content. By this, I mean that your paragraphs get cut off by the image on the left depending on how wide your browser window is. If you include the written content and images inside a grid, it might be easier for your website to maintain a better look between different browser screen dimensions.
- My Progress Page: try to format the labels on the page, both from which year the videos are as well as the song cover titles, you can easily add id's to  these elements and format them all at once using css. Also, edit the meta tags on your code to change the current page title from "Document" to "My Progress" on line 7
- My Advice & Chords to Learn pages: consider editing the css stylesheet in order to format the `<h2>` to be centered and match the formatting present on page titles like in the homepage and my progress page.
- Customer Feedback & Sitemap: add css stylesheets for both of these pages to match the looks of the rest of the website.

Once again, I really enjoyed having to work with your site and I can’t wait to see how your website looks like for the next peer review round!

**Comment by dannydonahue5** [comment]
Hi Enrique, 

Thank you for the feedback - I have taken your changes into account for the new version of my website, I have made a lot of edits since you commented and I just pushed them. Thank you again for providing insight and take a look at the updated version if you'd like. 

Best,
Danny
